/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * 国語授業進度管理 API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * Returns server health status
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * Returns all units with their lessons and progress
 * @summary List all units
 */
export declare const ListUnitsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    orderIndex: zod.ZodNumber;
    createdAt: zod.ZodString;
    lessons: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        unitId: zod.ZodNumber;
        title: zod.ZodString;
        memo: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        status: zod.ZodEnum<["upcoming", "in_progress", "completed"]>;
        lessonDate: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        orderIndex: zod.ZodNumber;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    }, {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    }>, "many">;
    completedCount: zod.ZodNumber;
    totalCount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    lessons: {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    }[];
    completedCount: number;
    totalCount: number;
    description?: string | null | undefined;
}, {
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    lessons: {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    }[];
    completedCount: number;
    totalCount: number;
    description?: string | null | undefined;
}>;
export declare const ListUnitsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    orderIndex: zod.ZodNumber;
    createdAt: zod.ZodString;
    lessons: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        unitId: zod.ZodNumber;
        title: zod.ZodString;
        memo: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        status: zod.ZodEnum<["upcoming", "in_progress", "completed"]>;
        lessonDate: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        orderIndex: zod.ZodNumber;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    }, {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    }>, "many">;
    completedCount: zod.ZodNumber;
    totalCount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    lessons: {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    }[];
    completedCount: number;
    totalCount: number;
    description?: string | null | undefined;
}, {
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    lessons: {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    }[];
    completedCount: number;
    totalCount: number;
    description?: string | null | undefined;
}>, "many">;
/**
 * @summary Create a unit
 */
export declare const CreateUnitBody: zod.ZodObject<{
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    orderIndex: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    title: string;
    description?: string | undefined;
    orderIndex?: number | undefined;
}, {
    title: string;
    description?: string | undefined;
    orderIndex?: number | undefined;
}>;
export declare const CreateUnitResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    orderIndex: zod.ZodNumber;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    description?: string | null | undefined;
}, {
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    description?: string | null | undefined;
}>;
/**
 * @summary Get a unit with its lessons
 */
export declare const GetUnitParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetUnitResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    orderIndex: zod.ZodNumber;
    createdAt: zod.ZodString;
    lessons: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        unitId: zod.ZodNumber;
        title: zod.ZodString;
        memo: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        status: zod.ZodEnum<["upcoming", "in_progress", "completed"]>;
        lessonDate: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        orderIndex: zod.ZodNumber;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    }, {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    }>, "many">;
    completedCount: zod.ZodNumber;
    totalCount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    lessons: {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    }[];
    completedCount: number;
    totalCount: number;
    description?: string | null | undefined;
}, {
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    lessons: {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    }[];
    completedCount: number;
    totalCount: number;
    description?: string | null | undefined;
}>;
/**
 * @summary Update a unit
 */
export declare const UpdateUnitParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateUnitBody: zod.ZodObject<{
    title: zod.ZodOptional<zod.ZodString>;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    orderIndex: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    title?: string | undefined;
    description?: string | null | undefined;
    orderIndex?: number | undefined;
}, {
    title?: string | undefined;
    description?: string | null | undefined;
    orderIndex?: number | undefined;
}>;
export declare const UpdateUnitResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    orderIndex: zod.ZodNumber;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    description?: string | null | undefined;
}, {
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    description?: string | null | undefined;
}>;
/**
 * @summary Delete a unit
 */
export declare const DeleteUnitParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const DeleteUnitResponse: zod.ZodVoid;
/**
 * @summary List all lessons
 */
export declare const ListLessonsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    unitId: zod.ZodNumber;
    title: zod.ZodString;
    memo: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["upcoming", "in_progress", "completed"]>;
    lessonDate: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    orderIndex: zod.ZodNumber;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "upcoming" | "in_progress" | "completed";
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    unitId: number;
    memo?: string | null | undefined;
    lessonDate?: string | null | undefined;
}, {
    status: "upcoming" | "in_progress" | "completed";
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    unitId: number;
    memo?: string | null | undefined;
    lessonDate?: string | null | undefined;
}>;
export declare const ListLessonsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    unitId: zod.ZodNumber;
    title: zod.ZodString;
    memo: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["upcoming", "in_progress", "completed"]>;
    lessonDate: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    orderIndex: zod.ZodNumber;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "upcoming" | "in_progress" | "completed";
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    unitId: number;
    memo?: string | null | undefined;
    lessonDate?: string | null | undefined;
}, {
    status: "upcoming" | "in_progress" | "completed";
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    unitId: number;
    memo?: string | null | undefined;
    lessonDate?: string | null | undefined;
}>, "many">;
/**
 * @summary Create a lesson
 */
export declare const CreateLessonBody: zod.ZodObject<{
    unitId: zod.ZodNumber;
    title: zod.ZodString;
    memo: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodEnum<["upcoming", "in_progress", "completed"]>>;
    lessonDate: zod.ZodOptional<zod.ZodString>;
    orderIndex: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    title: string;
    unitId: number;
    status?: "upcoming" | "in_progress" | "completed" | undefined;
    orderIndex?: number | undefined;
    memo?: string | undefined;
    lessonDate?: string | undefined;
}, {
    title: string;
    unitId: number;
    status?: "upcoming" | "in_progress" | "completed" | undefined;
    orderIndex?: number | undefined;
    memo?: string | undefined;
    lessonDate?: string | undefined;
}>;
export declare const CreateLessonResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    unitId: zod.ZodNumber;
    title: zod.ZodString;
    memo: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["upcoming", "in_progress", "completed"]>;
    lessonDate: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    orderIndex: zod.ZodNumber;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "upcoming" | "in_progress" | "completed";
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    unitId: number;
    memo?: string | null | undefined;
    lessonDate?: string | null | undefined;
}, {
    status: "upcoming" | "in_progress" | "completed";
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    unitId: number;
    memo?: string | null | undefined;
    lessonDate?: string | null | undefined;
}>;
/**
 * @summary Get a lesson
 */
export declare const GetLessonParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetLessonResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    unitId: zod.ZodNumber;
    title: zod.ZodString;
    memo: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["upcoming", "in_progress", "completed"]>;
    lessonDate: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    orderIndex: zod.ZodNumber;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "upcoming" | "in_progress" | "completed";
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    unitId: number;
    memo?: string | null | undefined;
    lessonDate?: string | null | undefined;
}, {
    status: "upcoming" | "in_progress" | "completed";
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    unitId: number;
    memo?: string | null | undefined;
    lessonDate?: string | null | undefined;
}>;
/**
 * @summary Update a lesson (including status)
 */
export declare const UpdateLessonParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateLessonBody: zod.ZodObject<{
    title: zod.ZodOptional<zod.ZodString>;
    memo: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodOptional<zod.ZodEnum<["upcoming", "in_progress", "completed"]>>;
    lessonDate: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    orderIndex: zod.ZodOptional<zod.ZodNumber>;
    unitId: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    status?: "upcoming" | "in_progress" | "completed" | undefined;
    title?: string | undefined;
    orderIndex?: number | undefined;
    unitId?: number | undefined;
    memo?: string | null | undefined;
    lessonDate?: string | null | undefined;
}, {
    status?: "upcoming" | "in_progress" | "completed" | undefined;
    title?: string | undefined;
    orderIndex?: number | undefined;
    unitId?: number | undefined;
    memo?: string | null | undefined;
    lessonDate?: string | null | undefined;
}>;
export declare const UpdateLessonResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    unitId: zod.ZodNumber;
    title: zod.ZodString;
    memo: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["upcoming", "in_progress", "completed"]>;
    lessonDate: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    orderIndex: zod.ZodNumber;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "upcoming" | "in_progress" | "completed";
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    unitId: number;
    memo?: string | null | undefined;
    lessonDate?: string | null | undefined;
}, {
    status: "upcoming" | "in_progress" | "completed";
    id: number;
    title: string;
    orderIndex: number;
    createdAt: string;
    unitId: number;
    memo?: string | null | undefined;
    lessonDate?: string | null | undefined;
}>;
/**
 * @summary Delete a lesson
 */
export declare const DeleteLessonParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const DeleteLessonResponse: zod.ZodVoid;
/**
 * Returns overall completion statistics and current progress
 * @summary Get overall progress summary
 */
export declare const GetProgressSummaryResponse: zod.ZodObject<{
    totalUnits: zod.ZodNumber;
    totalLessons: zod.ZodNumber;
    completedLessons: zod.ZodNumber;
    inProgressLessons: zod.ZodNumber;
    upcomingLessons: zod.ZodNumber;
    completionPercent: zod.ZodNumber;
    currentUnit: zod.ZodOptional<zod.ZodObject<{
        id: zod.ZodNumber;
        title: zod.ZodString;
        description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        orderIndex: zod.ZodNumber;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        description?: string | null | undefined;
    }, {
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        description?: string | null | undefined;
    }>>;
    currentLesson: zod.ZodOptional<zod.ZodObject<{
        id: zod.ZodNumber;
        unitId: zod.ZodNumber;
        title: zod.ZodString;
        memo: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        status: zod.ZodEnum<["upcoming", "in_progress", "completed"]>;
        lessonDate: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        orderIndex: zod.ZodNumber;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    }, {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    }>>;
}, "strip", zod.ZodTypeAny, {
    totalUnits: number;
    totalLessons: number;
    completedLessons: number;
    inProgressLessons: number;
    upcomingLessons: number;
    completionPercent: number;
    currentUnit?: {
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        description?: string | null | undefined;
    } | undefined;
    currentLesson?: {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    } | undefined;
}, {
    totalUnits: number;
    totalLessons: number;
    completedLessons: number;
    inProgressLessons: number;
    upcomingLessons: number;
    completionPercent: number;
    currentUnit?: {
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        description?: string | null | undefined;
    } | undefined;
    currentLesson?: {
        status: "upcoming" | "in_progress" | "completed";
        id: number;
        title: string;
        orderIndex: number;
        createdAt: string;
        unitId: number;
        memo?: string | null | undefined;
        lessonDate?: string | null | undefined;
    } | undefined;
}>;
//# sourceMappingURL=api.d.ts.map