/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * 国語授業進度管理 API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
export interface ErrorResponse {
    error: string;
}
export interface Unit {
    id: number;
    title: string;
    /** @nullable */
    description?: string | null;
    orderIndex: number;
    createdAt: string;
}
export type LessonStatus = typeof LessonStatus[keyof typeof LessonStatus];
export declare const LessonStatus: {
    readonly upcoming: "upcoming";
    readonly in_progress: "in_progress";
    readonly completed: "completed";
};
export interface Lesson {
    id: number;
    unitId: number;
    title: string;
    /** @nullable */
    memo?: string | null;
    status: LessonStatus;
    /** @nullable */
    lessonDate?: string | null;
    orderIndex: number;
    createdAt: string;
}
export interface UnitWithLessons {
    id: number;
    title: string;
    /** @nullable */
    description?: string | null;
    orderIndex: number;
    createdAt: string;
    lessons: Lesson[];
    completedCount: number;
    totalCount: number;
}
export interface UnitInput {
    /** @minLength 1 */
    title: string;
    description?: string;
    orderIndex?: number;
}
export interface UnitUpdate {
    /** @minLength 1 */
    title?: string;
    /** @nullable */
    description?: string | null;
    orderIndex?: number;
}
export type LessonInputStatus = typeof LessonInputStatus[keyof typeof LessonInputStatus];
export declare const LessonInputStatus: {
    readonly upcoming: "upcoming";
    readonly in_progress: "in_progress";
    readonly completed: "completed";
};
export interface LessonInput {
    unitId: number;
    /** @minLength 1 */
    title: string;
    memo?: string;
    status?: LessonInputStatus;
    lessonDate?: string;
    orderIndex?: number;
}
export type LessonUpdateStatus = typeof LessonUpdateStatus[keyof typeof LessonUpdateStatus];
export declare const LessonUpdateStatus: {
    readonly upcoming: "upcoming";
    readonly in_progress: "in_progress";
    readonly completed: "completed";
};
export interface LessonUpdate {
    /** @minLength 1 */
    title?: string;
    /** @nullable */
    memo?: string | null;
    status?: LessonUpdateStatus;
    /** @nullable */
    lessonDate?: string | null;
    orderIndex?: number;
    unitId?: number;
}
export interface ProgressSummary {
    totalUnits: number;
    totalLessons: number;
    completedLessons: number;
    inProgressLessons: number;
    upcomingLessons: number;
    completionPercent: number;
    currentUnit?: Unit;
    currentLesson?: Lesson;
}
//# sourceMappingURL=api.schemas.d.ts.map