/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * 国語授業進度管理 API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  HealthStatus,
  Lesson,
  LessonInput,
  LessonUpdate,
  ProgressSummary,
  Unit,
  UnitInput,
  UnitUpdate,
  UnitWithLessons
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * Returns server health status
 * @summary Health check
 */
export const healthCheck = async ( options?: Parameters<typeof customFetch>[1]): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListUnitsUrl = () => {




  return `/api/units`
}

/**
 * Returns all units with their lessons and progress
 * @summary List all units
 */
export const listUnits = async ( options?: Parameters<typeof customFetch>[1]): Promise<UnitWithLessons[]> => {

  return customFetch<UnitWithLessons[]>(getListUnitsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListUnitsQueryKey = () => {
    return [
    `/api/units`
    ] as const;
    }


export const getListUnitsQueryOptions = <TData = Awaited<ReturnType<typeof listUnits>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listUnits>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUnitsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUnits>>> = ({ signal }) => listUnits({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUnits>>, TError, TData> & { queryKey: QueryKey }
}

export type ListUnitsQueryResult = NonNullable<Awaited<ReturnType<typeof listUnits>>>
export type ListUnitsQueryError = ErrorType<unknown>


/**
 * @summary List all units
 */

export function useListUnits<TData = Awaited<ReturnType<typeof listUnits>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listUnits>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListUnitsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateUnitUrl = () => {




  return `/api/units`
}

/**
 * @summary Create a unit
 */
export const createUnit = async (unitInput: UnitInput, options?: Parameters<typeof customFetch>[1]): Promise<Unit> => {

  return customFetch<Unit>(getCreateUnitUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(unitInput)
  }
);}





export const getCreateUnitMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUnit>>, TError,{data: BodyType<UnitInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createUnit>>, TError,{data: BodyType<UnitInput>}, TContext> => {

const mutationKey = ['createUnit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUnit>>, {data: BodyType<UnitInput>}> = (props) => {
          const {data} = props ?? {};

          return  createUnit(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateUnitMutationResult = NonNullable<Awaited<ReturnType<typeof createUnit>>>
    export type CreateUnitMutationBody = BodyType<UnitInput>
    export type CreateUnitMutationError = ErrorType<unknown>

    /**
 * @summary Create a unit
 */
export const useCreateUnit = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUnit>>, TError,{data: BodyType<UnitInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createUnit>>,
        TError,
        {data: BodyType<UnitInput>},
        TContext
      > => {
      return useMutation(getCreateUnitMutationOptions(options));
    }

export const getGetUnitUrl = (id: number,) => {




  return `/api/units/${id}`
}

/**
 * @summary Get a unit with its lessons
 */
export const getUnit = async (id: number, options?: Parameters<typeof customFetch>[1]): Promise<UnitWithLessons> => {

  return customFetch<UnitWithLessons>(getGetUnitUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUnitQueryKey = (id: number,) => {
    return [
    `/api/units/${id}`
    ] as const;
    }


export const getGetUnitQueryOptions = <TData = Awaited<ReturnType<typeof getUnit>>, TError = ErrorType<ErrorResponse>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUnit>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUnitQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUnit>>> = ({ signal }) => getUnit(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUnit>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUnitQueryResult = NonNullable<Awaited<ReturnType<typeof getUnit>>>
export type GetUnitQueryError = ErrorType<ErrorResponse>


/**
 * @summary Get a unit with its lessons
 */

export function useGetUnit<TData = Awaited<ReturnType<typeof getUnit>>, TError = ErrorType<ErrorResponse>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUnit>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUnitQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getUpdateUnitUrl = (id: number,) => {




  return `/api/units/${id}`
}

/**
 * @summary Update a unit
 */
export const updateUnit = async (id: number,
    unitUpdate: UnitUpdate, options?: Parameters<typeof customFetch>[1]): Promise<Unit> => {

  return customFetch<Unit>(getUpdateUnitUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(unitUpdate)
  }
);}





export const getUpdateUnitMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUnit>>, TError,{id: number;data: BodyType<UnitUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUnit>>, TError,{id: number;data: BodyType<UnitUpdate>}, TContext> => {

const mutationKey = ['updateUnit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUnit>>, {id: number;data: BodyType<UnitUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateUnit(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateUnitMutationResult = NonNullable<Awaited<ReturnType<typeof updateUnit>>>
    export type UpdateUnitMutationBody = BodyType<UnitUpdate>
    export type UpdateUnitMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Update a unit
 */
export const useUpdateUnit = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUnit>>, TError,{id: number;data: BodyType<UnitUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateUnit>>,
        TError,
        {id: number;data: BodyType<UnitUpdate>},
        TContext
      > => {
      return useMutation(getUpdateUnitMutationOptions(options));
    }

export const getDeleteUnitUrl = (id: number,) => {




  return `/api/units/${id}`
}

/**
 * @summary Delete a unit
 */
export const deleteUnit = async (id: number, options?: Parameters<typeof customFetch>[1]): Promise<void> => {

  return customFetch<void>(getDeleteUnitUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteUnitMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUnit>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUnit>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteUnit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUnit>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteUnit(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUnitMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUnit>>>

    export type DeleteUnitMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete a unit
 */
export const useDeleteUnit = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUnit>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteUnit>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteUnitMutationOptions(options));
    }

export const getListLessonsUrl = () => {




  return `/api/lessons`
}

/**
 * @summary List all lessons
 */
export const listLessons = async ( options?: Parameters<typeof customFetch>[1]): Promise<Lesson[]> => {

  return customFetch<Lesson[]>(getListLessonsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListLessonsQueryKey = () => {
    return [
    `/api/lessons`
    ] as const;
    }


export const getListLessonsQueryOptions = <TData = Awaited<ReturnType<typeof listLessons>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listLessons>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListLessonsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listLessons>>> = ({ signal }) => listLessons({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listLessons>>, TError, TData> & { queryKey: QueryKey }
}

export type ListLessonsQueryResult = NonNullable<Awaited<ReturnType<typeof listLessons>>>
export type ListLessonsQueryError = ErrorType<unknown>


/**
 * @summary List all lessons
 */

export function useListLessons<TData = Awaited<ReturnType<typeof listLessons>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listLessons>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListLessonsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateLessonUrl = () => {




  return `/api/lessons`
}

/**
 * @summary Create a lesson
 */
export const createLesson = async (lessonInput: LessonInput, options?: Parameters<typeof customFetch>[1]): Promise<Lesson> => {

  return customFetch<Lesson>(getCreateLessonUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(lessonInput)
  }
);}





export const getCreateLessonMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLesson>>, TError,{data: BodyType<LessonInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createLesson>>, TError,{data: BodyType<LessonInput>}, TContext> => {

const mutationKey = ['createLesson'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLesson>>, {data: BodyType<LessonInput>}> = (props) => {
          const {data} = props ?? {};

          return  createLesson(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateLessonMutationResult = NonNullable<Awaited<ReturnType<typeof createLesson>>>
    export type CreateLessonMutationBody = BodyType<LessonInput>
    export type CreateLessonMutationError = ErrorType<unknown>

    /**
 * @summary Create a lesson
 */
export const useCreateLesson = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLesson>>, TError,{data: BodyType<LessonInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createLesson>>,
        TError,
        {data: BodyType<LessonInput>},
        TContext
      > => {
      return useMutation(getCreateLessonMutationOptions(options));
    }

export const getGetLessonUrl = (id: number,) => {




  return `/api/lessons/${id}`
}

/**
 * @summary Get a lesson
 */
export const getLesson = async (id: number, options?: Parameters<typeof customFetch>[1]): Promise<Lesson> => {

  return customFetch<Lesson>(getGetLessonUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLessonQueryKey = (id: number,) => {
    return [
    `/api/lessons/${id}`
    ] as const;
    }


export const getGetLessonQueryOptions = <TData = Awaited<ReturnType<typeof getLesson>>, TError = ErrorType<ErrorResponse>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLesson>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLessonQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLesson>>> = ({ signal }) => getLesson(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLesson>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLessonQueryResult = NonNullable<Awaited<ReturnType<typeof getLesson>>>
export type GetLessonQueryError = ErrorType<ErrorResponse>


/**
 * @summary Get a lesson
 */

export function useGetLesson<TData = Awaited<ReturnType<typeof getLesson>>, TError = ErrorType<ErrorResponse>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLesson>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetLessonQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getUpdateLessonUrl = (id: number,) => {




  return `/api/lessons/${id}`
}

/**
 * @summary Update a lesson (including status)
 */
export const updateLesson = async (id: number,
    lessonUpdate: LessonUpdate, options?: Parameters<typeof customFetch>[1]): Promise<Lesson> => {

  return customFetch<Lesson>(getUpdateLessonUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(lessonUpdate)
  }
);}





export const getUpdateLessonMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLesson>>, TError,{id: number;data: BodyType<LessonUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateLesson>>, TError,{id: number;data: BodyType<LessonUpdate>}, TContext> => {

const mutationKey = ['updateLesson'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLesson>>, {id: number;data: BodyType<LessonUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLesson(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateLessonMutationResult = NonNullable<Awaited<ReturnType<typeof updateLesson>>>
    export type UpdateLessonMutationBody = BodyType<LessonUpdate>
    export type UpdateLessonMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Update a lesson (including status)
 */
export const useUpdateLesson = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLesson>>, TError,{id: number;data: BodyType<LessonUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateLesson>>,
        TError,
        {id: number;data: BodyType<LessonUpdate>},
        TContext
      > => {
      return useMutation(getUpdateLessonMutationOptions(options));
    }

export const getDeleteLessonUrl = (id: number,) => {




  return `/api/lessons/${id}`
}

/**
 * @summary Delete a lesson
 */
export const deleteLesson = async (id: number, options?: Parameters<typeof customFetch>[1]): Promise<void> => {

  return customFetch<void>(getDeleteLessonUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteLessonMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLesson>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteLesson>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteLesson'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLesson>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteLesson(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteLessonMutationResult = NonNullable<Awaited<ReturnType<typeof deleteLesson>>>

    export type DeleteLessonMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete a lesson
 */
export const useDeleteLesson = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLesson>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteLesson>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteLessonMutationOptions(options));
    }

export const getGetProgressSummaryUrl = () => {




  return `/api/progress/summary`
}

/**
 * Returns overall completion statistics and current progress
 * @summary Get overall progress summary
 */
export const getProgressSummary = async ( options?: Parameters<typeof customFetch>[1]): Promise<ProgressSummary> => {

  return customFetch<ProgressSummary>(getGetProgressSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProgressSummaryQueryKey = () => {
    return [
    `/api/progress/summary`
    ] as const;
    }


export const getGetProgressSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getProgressSummary>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getProgressSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProgressSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProgressSummary>>> = ({ signal }) => getProgressSummary({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProgressSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetProgressSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getProgressSummary>>>
export type GetProgressSummaryQueryError = ErrorType<unknown>


/**
 * @summary Get overall progress summary
 */

export function useGetProgressSummary<TData = Awaited<ReturnType<typeof getProgressSummary>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getProgressSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetProgressSummaryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







