/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * 国語授業進度管理 API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
//# sourceMappingURL=healthStatus.d.ts.map