/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * 国語授業進度管理 API
 * OpenAPI spec version: 0.1.0
 */
import type { LessonInputStatus } from './lessonInputStatus';
export interface LessonInput {
    unitId: number;
    /** @minLength 1 */
    title: string;
    memo?: string;
    status?: LessonInputStatus;
    lessonDate?: string;
    orderIndex?: number;
}
//# sourceMappingURL=lessonInput.d.ts.map