/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * 国語授業進度管理 API
 * OpenAPI spec version: 0.1.0
 */
export type LessonStatus = typeof LessonStatus[keyof typeof LessonStatus];
export declare const LessonStatus: {
    readonly upcoming: "upcoming";
    readonly in_progress: "in_progress";
    readonly completed: "completed";
};
//# sourceMappingURL=lessonStatus.d.ts.map