/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * 国語授業進度管理 API
 * OpenAPI spec version: 0.1.0
 */
import type { LessonStatus } from './lessonStatus';
export interface Lesson {
    id: number;
    unitId: number;
    title: string;
    /** @nullable */
    memo?: string | null;
    status: LessonStatus;
    /** @nullable */
    lessonDate?: string | null;
    orderIndex: number;
    createdAt: string;
}
//# sourceMappingURL=lesson.d.ts.map