/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * 国語授業進度管理 API
 * OpenAPI spec version: 0.1.0
 */
export type LessonInputStatus = typeof LessonInputStatus[keyof typeof LessonInputStatus];
export declare const LessonInputStatus: {
    readonly upcoming: "upcoming";
    readonly in_progress: "in_progress";
    readonly completed: "completed";
};
//# sourceMappingURL=lessonInputStatus.d.ts.map