/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * 国語授業進度管理 API
 * OpenAPI spec version: 0.1.0
 */
export type LessonUpdateStatus = typeof LessonUpdateStatus[keyof typeof LessonUpdateStatus];
export declare const LessonUpdateStatus: {
    readonly upcoming: "upcoming";
    readonly in_progress: "in_progress";
    readonly completed: "completed";
};
//# sourceMappingURL=lessonUpdateStatus.d.ts.map