/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * 国語授業進度管理 API
 * OpenAPI spec version: 0.1.0
 */
import type { LessonUpdateStatus } from './lessonUpdateStatus';
export interface LessonUpdate {
    /** @minLength 1 */
    title?: string;
    /** @nullable */
    memo?: string | null;
    status?: LessonUpdateStatus;
    /** @nullable */
    lessonDate?: string | null;
    orderIndex?: number;
    unitId?: number;
}
//# sourceMappingURL=lessonUpdate.d.ts.map