/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * 国語授業進度管理 API
 * OpenAPI spec version: 0.1.0
 */
import type { Lesson } from './lesson';
import type { Unit } from './unit';
export interface ProgressSummary {
    totalUnits: number;
    totalLessons: number;
    completedLessons: number;
    inProgressLessons: number;
    upcomingLessons: number;
    completionPercent: number;
    currentUnit?: Unit;
    currentLesson?: Lesson;
}
//# sourceMappingURL=progressSummary.d.ts.map