/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * 国語授業進度管理 API
 * OpenAPI spec version: 0.1.0
 */
import type { Lesson } from './lesson';
export interface UnitWithLessons {
    id: number;
    title: string;
    /** @nullable */
    description?: string | null;
    orderIndex: number;
    createdAt: string;
    lessons: Lesson[];
    completedCount: number;
    totalCount: number;
}
//# sourceMappingURL=unitWithLessons.d.ts.map